### ISSUE TITLE
Some topics may not need "Find related services near me" functionality

### ISSUE THREAD

**Issue by jparlina** [pg-irc/pathways-frontend#541]
At our presentation to Surrey Immigrant Advisory Roundtable at the Surrey City Hall yesterday, someone searched services under the topic “Sending money to other countries” - the first search result listed was HandyDART Metro Vancouver.

I tested at home in Burnaby → none of the services listed were about sending money to other countries:
- HandyDARTMetro Vancouver was at the top - the description contains the words “cash”, “credit card”, “cheques/money orders”. 
- First United Community Services - the description contains the words “income”
- The rest of the search results listed Service Canada Centre at various locations - the description contains the words “tax credits”, “direct deposits”.

Maybe remove topics such as “Sending money to other countries” on AA since there is no relevant result within BC211. I tested BC211 data by searching using keywords “sending money”, no relevant results came out. 

Would it be possible to remove "Find related services near me" for topics that provide background info from Newcomers Guide, but with no relevant services related to the topic? It'll cause more confusion if we present irrelevant services. Or refine search criteria? 
For example:
- Canadian Money (search results include Vancouver Estonian Society, Vancouver Maritime Museum, Meals on Wheel Society, HandyDART Metro Vancouver, Coast Mental Health Resource Centre and other services where the description contains $
- Banking by phone, Internet, and smartphone (search results include Best Birth Clinic, Cancer Car Program, counselling services

**Comment by jparlina** [comment]
@rasmus-storjohann-PG @ArtiBPG Can we move this to high priority? Thx

**Comment by jparlina** [comment]
Tested Staging V 1.0.23 on iOS at the HiVE:

The following topics are resolved (i.e. No related services found):
- Acronyms and Abbreviations
- Canadian Money
- Compassionate care leave and benefits
- Metric and Imperial Measure
- Register for the Medical Services Plan (MSP)
- Sending and receiving mail
- Social Customs
- Telephone

**Comment by jparlina** [comment]
Tested Staging V 1.0.23 on iOS at the HiVE: 

The following topics have some services listed - looks like manual recommendations (not sure how relevant the services that would come up in other locations):

- Make a checklist before you move in: now just showing one service: Vancouver Tenants Union (VTU) 
- Make a checklist before you move out: now just showing one service: Vancouver Tenants Union (VTU)
- Traffic Laws: now showing ICBC offices

**Comment by jparlina** [comment]
Tested Staging V 1.0.23 on iOS at the HiVE:

The following topics still recommends irrelevant services:

- Apply for the Canada Child Benefit for children under 18 years old

- Car crashes: included ICBC Fairness Commissioner, RCMP (only UBC and Bowen Island locations - not really nearby locations)

- For more information on money management - includes LINC classes

- Give your Canadian address to IRCC

- How to use directories and the Internet: recommended libraries 

- Medical emergencies and hospital costs: only showing one result - Richmond Hospital (not the closest hospital from the HiVE, maybe other hospitals are not listed on bc211)

- Opening a bank account: includes LINC classes

- Prescription drugs 

- Personal Safety: the first service recommended is YWCA - Aboriginal Infant Development Program; other services are VPD and RCMP locations (ok)

- Sending money to other countries:  includes LINC classes

- Taking leave from work due to sickness

**Comment by ArtiBPG** [comment]
These topics still show services: 

> * **Apply for the Canada Child Benefit for Children under 18 years old**

> * **Car crashes**

Shows ICBC and RCMP (UBC) for Burnaby. I would suggest removing services entirely from this topic as the description itself has a link to ICBC.

> * **For more information on money management** - currently search results from PG office under this topic include BBB, Community Action Program for Children, Port Coquitlam Community Police Station, _Workshops and Training, Financial Literacy Programs. Only the last two are relevant services._
This should show only financial literacy programs. Now it shows language programs (from Burnaby)
> * **Give your Canadian address to Immigration, Refugees and Citizenship Canada**

Still shows services

> * **How to use directories and the Internet**

Still shows services

> * **Make a checklist before you move in**

Still shows services

> * **Make a checklist before you move out**

Still shows services

> * **Medical emergencies and hospital costs** - currently search results from PG office under this topic include BC Ambulance Service (ok), Older Adult Mental Health Program - West Vancouver, Better At Home - Richmond, GetCheckedOnline, Best Birth Clinic

Still shows services

> * **Metric and Imperial Measure**
> * **Opening a bank account**
> * **Prescription drugs** - unless the app can show the nearest pharmacies and Pharmacare offices, we should remove the "Find related services near me" since the search results are now irrelevant e.g. Vancouver Area Network of Drug Users, Green Cross Society of BC, BC Pharmacy Association, Insite, Pier Health Resource Centre (which support people with mental health and addiction issues), Drug Programs, Interim Federal Health Program, UBC Pharmacists Clinic, BC/Yukon Association of Drug War Survivors.
> * **Personal Safety** - currently search results from PG office under this topic only shows North Vancouver City Library
> * **Register for the Medical Services Plan (MSP)** - no physical office
> * **Sending and receiving mail** - unless we can show the nearest Canada Post locations and courier services (which are not in bc211 database), the "Find related services near me" should be removed.
> * **Sending money to other countries**
> * **Social Customs**
> * **Taking leave from work due to sickness**
> * **Telephone** - currently search results from PG office under this topic include Seniors Shopping Services, Better at Home Program, Access and Assessment Centre (AAC), anger Car Program, Best Birth Clinic
> * **Traffic Laws** - currently search results from PG office under this topic include Better At Home Program, North Shore Seniors Rideline, GetCheckedOnline (a free, confidential online testing services for chlamydia, gonorrhoea, syphilis, HIV, and hepatitis C), Cancer Car Program, Seniors Connect Program, Strive Centres, Best Birth Clinic
> 
> From reviewing the search results so far, I think we'll need to revisit what would be the best way of searching services since the NLP search seems to be problematic given the inconsistent description of each organization in bc211 database.

**Comment by tomy-pg** [comment]
The reason why a lot of the topics are still showing services is because of how we have ordered our prepare_deploy script. 

Our prepare_deploy.sh script has this ordering: 

1. remove similarity scores from topics where we do not want to show services 
2. add manual similarity scores for topics  

The reason some of these topics are still showing is because they have manual recommendations for them.

**Comment by jparlina** [comment]
Tested Staging V 1.0.25 on iOS 12.3.1 at the HiVE:
Confirmed all topics listed above no longer have services recommended

**Comment by tomy-pg** [comment]
For the most recent server release (v1.3.8) the data previously QA'd has been re-uploaded.

**Comment by jparlina** [comment]
Tested on iOS 12.4.1 - Staging V 1.2.0; Server V1.3.8; Jun 2019 bc211 dataset on Sep 3, 2019 at the HiVE

Confirmed the following topics no longer have services recommended: 
- [x] Acronyms and Abbreviations
- [x] Canadian Money
- [x] Compassionate care leave and benefits
- [x] Give your Canadian address to Immigration, Refugees and Citizenship Canada
- [x] Make a checklist before you move in
- [x] Make a checklist before you move out
- [x] Metric and Imperial Measure
- [x] Register for the Medical Services Plan (MSP) - no physical office
- [x] Sending and receiving mail
- [x] Social Customs
- [x] Telephone

Also confirmed the following topics no longer have services recommended as per[ issue #743 ](https://app.zenhub.com/workspaces/arrival-advisor-5977956f40fbe90e67bb4155/issues/pg-irc/pathways-frontend/743)
- [x] banking-by-phone-internet-and-smartphone
- [x] buying-a-home
- [x] buying-a-new-or-used-vehicle-car-or-truck
- [x] child-car-seats
- [x] distributed-distance-learning-and-homeschooling-for-children
- [x] doing-business-with-private-companies
- [x] adults-completing-secondary-school
- [x] safe-driving-resources

As per[ issue #743 ](https://app.zenhub.com/workspaces/arrival-advisor-5977956f40fbe90e67bb4155/issues/pg-irc/pathways-frontend/743), the following topics have manual recommendations from Sep 2018 data (will need to REVIEW recommended services from Jun 2019 data before Sep 2019 release):
- apply-for-the-canada-child-benefit-for-children-under-18-years-old (POOR recommendations)
- for-more-information-on-money-managementneed (POOR recommendations)
- prescription-drugs (POOR recommendations)
- opening-a-bank-account (POOR recommendations)
- personal-safety (POOR recommendations)
- sending-money-to-other-countries (POOR recommendations)
- taking-leave-from-work-due-to-sickness (POOR recommendations)
- traffic-laws (POOR recommendations)
- how-to-use-directories-and-the-internet (some IRRELEVANT services)
- car-crashes (need to review recommendations before Sep 2019 release)
- medical-emergencies-and-hospital-costs (need to review recommendations before Sep 2019 release)
